//
// Created by roland on 2019-12-17.
//

#ifndef CATASTROPHIC_CHIP8_INSTRUCTIONS_H
#define CATASTROPHIC_CHIP8_INSTRUCTIONS_H

#include "vm.h"

void CHIP8INSTR_0NNN(CH8_VM *vm);

void CHIP8INSTR_00E0(CH8_VM *vm);

void CHIP8INSTR_00EE(CH8_VM *vm);

void CHIP8INSTR_1NNN(CH8_VM *vm);

void CHIP8INSTR_2NNN(CH8_VM *vm);

void CHIP8INSTR_3XKK(CH8_VM *vm);

void CHIP8INSTR_4XKK(CH8_VM *vm);

void CHIP8INSTR_5XY0(CH8_VM *vm);

void CHIP8INSTR_6XKK(CH8_VM *vm);

void CHIP8INSTR_7XKK(CH8_VM *vm);

void CHIP8INSTR_8XY0(CH8_VM *vm);

void CHIP8INSTR_8XY1(CH8_VM *vm);

void CHIP8INSTR_8XY2(CH8_VM *vm);

void CHIP8INSTR_8XY3(CH8_VM *vm);

void CHIP8INSTR_8XY4(CH8_VM *vm);

void CHIP8INSTR_8XY5(CH8_VM *vm);

void CHIP8INSTR_8XY6(CH8_VM *vm);

void CHIP8INSTR_8XY7(CH8_VM *vm);

void CHIP8INSTR_8XYE(CH8_VM *vm);

void CHIP8INSTR_9XY0(CH8_VM *vm);

void CHIP8INSTR_ANNN(CH8_VM *vm);

void CHIP8INSTR_BNNN(CH8_VM *vm);

void CHIP8INSTR_CXKK(CH8_VM *vm);

void CHIP8INSTR_DXYN(CH8_VM *vm);

void CHIP8INSTR_EX9E(CH8_VM *vm);

void CHIP8INSTR_EXA1(CH8_VM *vm);

void CHIP8INSTR_FX07(CH8_VM *vm);

void CHIP8INSTR_FX0A(CH8_VM *vm);

void CHIP8INSTR_FX15(CH8_VM *vm);

void CHIP8INSTR_FX18(CH8_VM *vm);

void CHIP8INSTR_FX1E(CH8_VM *vm);

void CHIP8INSTR_FX29(CH8_VM *vm);

void CHIP8INSTR_FX33(CH8_VM *vm);

void CHIP8INSTR_FX55(CH8_VM *vm);

void CHIP8INSTR_FX65(CH8_VM *vm);

#endif //CATASTROPHIC_CHIP8_INSTRUCTIONS_H
