//
// Created by roland on 2019-12-17.
//

#ifndef CATASTROPHIC_CHIP8_INSTRUCTIONS_H
#define CATASTROPHIC_CHIP8_INSTRUCTIONS_H

#include "vm.h"

void CHIP8INSTR_0NNN(CHIP8_VM *vm);

void CHIP8INSTR_00E0(CHIP8_VM *vm);

void CHIP8INSTR_00EE(CHIP8_VM *vm);

void CHIP8INSTR_1NNN(CHIP8_VM *vm);

void CHIP8INSTR_2NNN(CHIP8_VM *vm);

void CHIP8INSTR_3XKK(CHIP8_VM *vm);

void CHIP8INSTR_4XKK(CHIP8_VM *vm);

void CHIP8INSTR_5XY0(CHIP8_VM *vm);

void CHIP8INSTR_6XKK(CHIP8_VM *vm);

void CHIP8INSTR_7XKK(CHIP8_VM *vm);

void CHIP8INSTR_8XY0(CHIP8_VM *vm);

void CHIP8INSTR_8XY1(CHIP8_VM *vm);

void CHIP8INSTR_8XY2(CHIP8_VM *vm);

void CHIP8INSTR_8XY3(CHIP8_VM *vm);

void CHIP8INSTR_8XY4(CHIP8_VM *vm);

void CHIP8INSTR_8XY5(CHIP8_VM *vm);

void CHIP8INSTR_8XY6(CHIP8_VM *vm);

void CHIP8INSTR_8XY7(CHIP8_VM *vm);

void CHIP8INSTR_8XYE(CHIP8_VM *vm);

void CHIP8INSTR_9XY0(CHIP8_VM *vm);

void CHIP8INSTR_ANNN(CHIP8_VM *vm);

void CHIP8INSTR_BNNN(CHIP8_VM *vm);

void CHIP8INSTR_CXKK(CHIP8_VM *vm);

void CHIP8INSTR_DXYN(CHIP8_VM *vm);

void CHIP8INSTR_EX9E(CHIP8_VM *vm);

void CHIP8INSTR_EXA1(CHIP8_VM *vm);

void CHIP8INSTR_FX07(CHIP8_VM *vm);

void CHIP8INSTR_FX0A(CHIP8_VM *vm);

void CHIP8INSTR_FX15(CHIP8_VM *vm);

void CHIP8INSTR_FX18(CHIP8_VM *vm);

void CHIP8INSTR_FX1E(CHIP8_VM *vm);

void CHIP8INSTR_FX29(CHIP8_VM *vm);

void CHIP8INSTR_FX33(CHIP8_VM *vm);

void CHIP8INSTR_FX55(CHIP8_VM *vm);

void CHIP8INSTR_FX65(CHIP8_VM *vm);

#endif //CATASTROPHIC_CHIP8_INSTRUCTIONS_H
